name: Build Executables

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual trigger from GitHub UI

permissions:
  contents: write  # Required for creating releases

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        include:
          - os: windows-latest
            output_name: CSV_Unique_Counter.exe
            renamed_file: CSV_Unique_Counter_Windows.exe
            artifact_name: CSV_Unique_Counter_Windows
          - os: macos-latest
            output_name: CSV_Unique_Counter
            renamed_file: CSV_Unique_Counter_Mac
            artifact_name: CSV_Unique_Counter_Mac
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller duckdb
    
    - name: Build executable (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        pyinstaller --onefile --name "CSV_Unique_Counter" csv_unique_counter.py
    
    - name: Build executable (Mac)
      if: matrix.os == 'macos-latest'
      run: |
        pyinstaller --onefile --windowed --name "CSV_Unique_Counter" csv_unique_counter.py
    
    - name: Rename executable (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        mv dist/${{ matrix.output_name }} dist/${{ matrix.renamed_file }}
    
    - name: Rename executable (Mac)
      if: matrix.os == 'macos-latest'
      run: |
        mv dist/${{ matrix.output_name }} dist/${{ matrix.renamed_file }}
    
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: dist/${{ matrix.renamed_file }}
        retention-days: 90

  create-release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    
    steps:
    - name: Download Windows executable
      uses: actions/download-artifact@v4
      with:
        name: CSV_Unique_Counter_Windows
        path: ./artifacts/windows
    
    - name: Download Mac executable
      uses: actions/download-artifact@v4
      with:
        name: CSV_Unique_Counter_Mac
        path: ./artifacts/mac
    
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.0.${{ github.run_number }}
        name: Release v1.0.${{ github.run_number }}
        draft: false
        prerelease: false
        files: |
          ./artifacts/windows/CSV_Unique_Counter_Windows.exe
          ./artifacts/mac/CSV_Unique_Counter_Mac
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

